INSERT INTO `user` (
		`id`,
		`uuid`,
		`first_name`,
		`last_name`,
		`middle_name`,
		`gender`,
		`address`,
		`birthday`,
		`role`,
		`email`,
		`number`,
		`active`,
		`password`,
		`password_unsafe`,
		`fathers_name`,
		`mothers_name`,
		`fathers_occupation`,
		`mothers_occupation`,
		`created_at`,
		`updated_at`
	)
VALUES (
		1,
		'WPErH6304q',
		'admin',
		'admin',
		NULL,
		NULL,
		NULL,
		NULL,
		'Admin',
		'admin@gmail.com',
		'09123456789',
		1,
		'$2y$10$fUrb4lb6EM7nHmrr0NWwo.X3zHzoyxlUWkhHIe1lzC6sYZqYBZYBm',
		'admin',
		NULL,
		NULL,
		NULL,
		NULL,
		'2021-04-30 12:40:15',
		'2021-04-30 12:40:15'
	);